name: Build wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-11]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cython
          python -m pip install regex
          python -m pip install future
          python -m pip install build
          python -m pip install cibuildwheel==2.12.3

      - name: Prebuild test
        run: |
          make test

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
