name: Build and upload to Pypi

on:
  release:
    types: [published]

jobs:
  make_sdist:
    name: Make SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.ADDITIONAL_TOKEN }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install regex
          python -m pip install cython

      - name: Prepare for build
        run: |
          make prepare

      - name: Build SDist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  build_wheels:
    name: Build wheels using the sdist
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest          
          - macos-latest
    needs:
      - make_sdist
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: sdist
          path: artifact
      - uses: actions/setup-python@v4
      - run: mv artifact/* ./sdist.tar.gz
      - run: ls -R
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cython
          python -m pip install regex
          python -m pip install future
          python -m pip install build
          python -m pip install cibuildwheel==2.12.3
      - name: actually build it
        uses: pypa/cibuildwheel@v2.23.2
        with:
          package-dir: sdist.tar.gz
          output-dir: wheelhouse
      - name: Save wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  publish_wheels:
    name: Publish Wheels to PyPI
    runs-on: ubuntu-latest
    needs:
      - build_wheels

    steps:
      - uses: actions/setup-python@v4

      - uses: actions/download-artifact@v4
        with:
          name: wheels-ubuntu-latest
          path: dist

      - uses: actions/download-artifact@v4
        with:
          name: wheels-windows-latest
          path: dist

      - uses: actions/download-artifact@v4
        with:
          name: wheels-macos-latest
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  publish_sdist:
    name: Publish sdist to PyPI
    runs-on: ubuntu-latest
    needs:
      - make_sdist
    steps:
      - uses: actions/setup-python@v4

      - uses: actions/download-artifact@v4
        with:
          name: sdist
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
